-- ===========================================================================
-- FilmStash Bot - Supabase / PostgreSQL schema
--
-- HOW TO RUN
--   1. Open your project at https://supabase.com/dashboard
--   2. Go to "SQL Editor" -> "New query"
--   3. Paste this entire file and click "Run".
--
-- The script is idempotent: running it twice will not raise errors.
-- ===========================================================================

-- Needed for gen_random_uuid() on PostgreSQL < 13. On Supabase this extension
-- is normally already enabled, but IF NOT EXISTS makes it safe to re-run.
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Table: movies
-- One row per (user, movie) log entry. `user_id` is the Telegram numeric ID
-- and is what isolates each user's library from every other user's.
-- ---------------------------------------------------------------------------
create table if not exists public.movies (
    -- Surrogate primary key generated by the database.
    id              uuid        primary key default gen_random_uuid(),

    -- Telegram numeric user id (e.g. 123456789). NOT NULL because every row
    -- must belong to exactly one user. bigint covers Telegram's id range.
    user_id         bigint      not null,

    -- Telegram @username at the time of logging. Nullable because a user may
    -- not have set a username. Stored for display/debugging convenience only;
    -- never use it for authorization - always filter by user_id.
    username        text,

    -- Movie title as resolved from TMDB (falls back to the user's input).
    title           text        not null,

    -- The user's own score, constrained to the 1-10 scale the bot enforces.
    personal_rating integer     not null
                    check (personal_rating between 1 and 10),

    -- TMDB's vote_average (0-10, one decimal). Nullable: TMDB sometimes has
    -- no votes yet for very new or obscure titles.
    imdb_rating     numeric(3,1)
                    check (imdb_rating is null or imdb_rating between 0 and 10),

    -- Fully-qualified poster URL, e.g.
    -- https://image.tmdb.org/t/p/w500/abc123.jpg
    poster_url      text,

    -- Short plot / overview text from TMDB.
    plot            text,

    -- Insert timestamp, always stored in UTC.
    created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- /list filters by user_id and orders by created_at desc. A composite index
-- lets Postgres satisfy both the filter and the sort from a single scan.
create index if not exists movies_user_id_created_at_idx
    on public.movies (user_id, created_at desc);

-- /search looks up a single title for one user. A case-insensitive functional
-- index keeps that lookup fast as the table grows.
create index if not exists movies_user_id_lower_title_idx
    on public.movies (user_id, lower(title));

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- The bot connects with the service_role key, which bypasses RLS entirely.
-- We still ENABLE RLS with no permissive policies so that the public `anon`
-- key cannot read or write this table if it is ever leaked into a client.
-- ---------------------------------------------------------------------------
alter table public.movies enable row level security;

-- ---------------------------------------------------------------------------
-- Optional: prevent the exact same title being logged twice by one user.
-- Uncomment if you prefer an upsert-style library over a history log.
-- ---------------------------------------------------------------------------
-- create unique index if not exists movies_user_id_lower_title_uniq
--     on public.movies (user_id, lower(title));

-- ---------------------------------------------------------------------------
-- Verification query - run after the script to confirm the table exists.
-- ---------------------------------------------------------------------------
-- select column_name, data_type, is_nullable, column_default
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'movies'
-- order by ordinal_position;
